---
policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
        # jira:
        #   keys:
        #   - DEVOPS
        #   - NAVY
      body:
        required: false
      dco: false
      gpg:
        required: false
        identity:
          gitHubOrganization: LiveIntent
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - revert
          - style
          - test
        scopes:
          - ".*"
        descriptionLength: 72
