branches:
  - master

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/git"

verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/git"

prepare:
  - path: "@semantic-release/changelog"
    changelogFile: CHANGELOG.md
  - path: "@semantic-release/npm"
  - path: "@semantic-release/git"
    assets:
      - package.json
      - package-lock.json
      - CHANGELOG.md
    message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'

publish:
  - path: "@semantic-release/npm"
  - path: "@semantic-release/github"
    assets:
      - dist/**

success:
  - path: "@semantic-release/github"

fail:
  - path: "@semantic-release/github"
