{
 "title": "Folding@home exporter dashboard",
 "tags": [
  "fah",
  "foldingathome"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team_users",
    "query": {
     "query": "label_values(foldingathome_team_users_rank,user)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "FAH Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (job) (foldingathome_up{job=\"fah_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAH User status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Rank",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(user) (foldingathome_user_rank{user=~\".*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User score",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(user) (foldingathome_user_score{user=~\".*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User activity",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "avg by(user) (foldingathome_user_active_7_days{user=~\".*\"})",
       "legendFormat": "Active 7 days"
      },
      {
       "expr": "avg by(user) (foldingathome_user_active_50_days{user=~\".*\"})",
       "legendFormat": "Active 50 days"
      }
     ]
    },
    {
     "title": "Workiung units",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "avg by (user) (foldingathome_user_wus{user=~\".*\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "FAH Team statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Team rank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "avg by (team_id) (foldingathome_team_rank{team_id=~\".*\"})",
       "legendFormat": "Team ID: {{team_id}}"
      }
     ]
    },
    {
     "title": "Team score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "avg by (team_id) (foldingathome_team_score{team_id=~\".*\"})",
       "legendFormat": "Team ID: {{team_id}}"
      }
     ]
    },
    {
     "title": "Team work units",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "avg by (team_id) (foldingathome_team_work_units{team_id=~\".*\"})",
       "legendFormat": "Team ID: {{team_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FAH Team status for user $team_users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "team_users",
   "collapsed": true,
   "panels": [
    {
     "title": "Group users rank",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "avg by (user) (foldingathome_team_users_rank{user=~\"$team_users\"})",
       "legendFormat": "Username: {{user}}"
      }
     ]
    },
    {
     "title": "User score",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "avg by (user) (foldingathome_team_users_score{user=~\"$team_users\"})",
       "legendFormat": "Username: {{user}}"
      }
     ]
    },
    {
     "title": "User work units",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "avg by (user) (foldingathome_team_users_wus{user=~\"$team_users\"})",
       "legendFormat": "Username: {{user}}"
      }
     ]
    }
   ]
  }
 ]
}